<a href="https://colab.research.google.com/github/DavidAlexandreTS/Machine-Learning-2020.2/blob/main/Machine_Learning_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
import pandas as pd
import numpy as np
import random as rd
import matplotlib.pyplot as plt
import xlrd
import seaborn as sns
from sklearn.cluster import KMeans

In [128]:
np.set_printoptions(threshold=sys.maxsize)

ind = "ID"
features = ["AL", "ACD", "WTW", "K1", "K2"]

data_frame = pd.read_excel("/content/barrettII_eyes_clustering.xlsx", index_col = ind)

X_cl = data_frame[features]

Y_cl = data_frame["Correto"]

X_cl = X_cl.astype(np.dtype('float64'))

In [129]:
k_means = KMeans(n_clusters = 8, random_state = 0).fit(X_cl[features])

In [130]:
groups = k_means.labels_

In [131]:
# Show the centroids of the groups
for i in range(0, 8):
  print("Centroid of the Group", i + 1, ":")
  print(kmeans.cluster_centers_[i])
  print()

Centroid of the Group 1 :
[24.13130952  3.39869048 12.02083333 43.9752381  44.9452381 ]

Centroid of the Group 2 :
[23.52092664  3.0142471  12.05907336 42.20540541 43.00405405]

Centroid of the Group 3 :
[22.62903537  2.98366559 11.76672026 44.84096463 45.76961415]

Centroid of the Group 4 :
[22.35638298  3.03900709 11.6106383  46.40177305 47.52553191]

Centroid of the Group 5 :
[24.974       3.49909677 12.26258065 42.62980645 43.49058065]

Centroid of the Group 6 :
[27.90125  3.31625 12.3125  34.36125 36.67625]

Centroid of the Group 7 :
[23.08819767  2.95938953 11.96075581 43.45462209 44.26895349]

Centroid of the Group 8 :
[24.75373239  3.18359155 12.28802817 40.72387324 41.62450704]



In [132]:
X_cl["Group ID"] = groups
X_cl["Correto"] = Y_cl

In [133]:
groups_profile = []
groups_percent = []

In [134]:
for i in range(0, 8):
  G = X_cl.loc[X_cl['Group ID'] == i]
  tt_G = G['Correto'].value_counts()/G['Correto'].count()*100
  qtd_SG = tt_G["S"]
  qtd_NG = tt_G["N"]
  groups_profile.append(G)
  groups_percent.append(qtd_SG)

In [145]:
# Display group profiles
for i in range(0, 8):
  print("         ****** The Group",i + 1,"have", groups_profile[i].shape[0],"members ******")
  print("-------- Information from individuals in Group", i + 1, "--------")
  print(groups_profile[i])
  print()
  print()

         ****** The Group 1 have 166 members ******
-------- Information from individuals in Group 1 --------
         AL   ACD   WTW     K1     K2  Group ID Correto
ID                                                     
6     23.73  2.87  12.0  43.21  45.12         0       S
19    24.08  3.21  12.0  43.44  44.76         0       S
26    23.63  2.85  11.5  42.99  45.42         0       S
30    23.60  3.60  11.9  43.32  45.42         0       N
34    23.86  3.71  12.3  43.83  45.00         0       S
...     ...   ...   ...    ...    ...       ...     ...
1471  24.13  3.66  12.0  43.89  44.06         0       N
1474  23.38  3.12  11.8  44.18  45.18         0       S
1479  24.02  3.20  12.1  43.60  44.06         0       S
1494  24.88  2.58  11.4  43.95  44.82         0       N
1527  23.99  3.09  11.8  44.70  45.30         0       N

[166 rows x 7 columns]


         ****** The Group 2 have 259 members ******
-------- Information from individuals in Group 2 --------
         AL   ACD   WTW   

In [146]:
for i in range(0, 8):
  print("Data for the Group", i + 1)
  print("The frequency of YES is approximately:", round(groups_percent[i]),"%")
  print("The frequency of NO is approximately:", 100 - round(groups_percent[i]),"%")
  print()

Data for the Group 1
The frequency of YES is approximately: 67 %
The frequency of NO is approximately: 33 %

Data for the Group 2
The frequency of YES is approximately: 71 %
The frequency of NO is approximately: 29 %

Data for the Group 3
The frequency of YES is approximately: 72 %
The frequency of NO is approximately: 28 %

Data for the Group 4
The frequency of YES is approximately: 60 %
The frequency of NO is approximately: 40 %

Data for the Group 5
The frequency of YES is approximately: 74 %
The frequency of NO is approximately: 26 %

Data for the Group 6
The frequency of YES is approximately: 25 %
The frequency of NO is approximately: 75 %

Data for the Group 7
The frequency of YES is approximately: 75 %
The frequency of NO is approximately: 25 %

Data for the Group 8
The frequency of YES is approximately: 71 %
The frequency of NO is approximately: 29 %

